Revert "[test] switch to detailed-0.9"
Getting weird cabal errors on ghc 7.10, 8.0:

    Running 1 test suites...
    Test suite test: RUNNING...
    panic! read @TestSuiteLog ""
    CallStack (from HasCallStack):
      error, called at src\Distribution\Simple\Test\LibV09.hs:159:28 in Cabal-3.12.1.0-inplace:Distribution.Simple.Test.LibV09
    Error: [Cabal-7125]

This reverts commit eb57139b401f676ba115fc03ba0b5fafd9135b44.